sudo: required

services:
  - docker

before_install:
  - docker build -t jhaab1:react_image -f Dockerfile.dev .

script:
  - docker run -e CI=true jhaab1:react_image npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-293394632058"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY